# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://cieyongwe.com'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: ''

logo: "/uploads/logo-mini.png"

# Title of the Site
title: Cie Yongwe
# Description of the Site
description: Spectacles vivants et cie
# URL of Image of the Site
site-image: /uploads/logo-mini.png
# Keywords of the Site
site-keywords: Spectacle, Compagnie, Po√©sie, Musique
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /uploads/dome-lune-light.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: compagnie.yongwe@gmail.com
facebook_username: cieyongwe
youtube_channel_id: "@cieyongwe3136"
instagram_username: "cie.yongwe"

# Google Analytics
google-analytics: 


# Name of the Author
author-name: Cie Yongwe
# URL for the Image of the Author
author-image: "/uploads/logo-mini.png"
# 60 Words About the Author
author-about: Spectacles vivants et cie.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)


# Defaults
defaults:
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
